spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_db
    username: suda
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: 422dda7d09e1b0808b87e64bf71d9d43
            client-secret: tXMl87rJ0F9EchFVXeOrVN02S68RrR5s
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope:
              - profile_nickname
              - profile_image

        provider:
          kakao:
            user-name-attribute: id
            user-info-authentication-method: header
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

allowOrigin: http://localhost:5173
