spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_db
    username: suda
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
