spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_db
    username: suda
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${kakao-id}
            client-secret: ${kakao-secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope:
              - profile_nickname
              - profile_image
          google:
            client-id: ${google-id}
            client-secret: ${google-secret}
            scope:
              - email
              - profile

        provider:
          kakao:
            user-name-attribute: id
            user-info-authentication-method: header
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

allow-origin: http://localhost:5173
jwt-secret: ${jwt-secret}
